mysql:
  host: localhost
  port: 3306
  user: your_mysql_user
  password: your_mysql_password
  database: your_mysql_database

mongodb:
  uri: mongodb://localhost:27017/
  database: your_mongo_database

jwt:
  secret_key: your_secret_key
  access_token_expires: 3600

tables:
  - mysql_table: table1
    mongo_collection: collection1
  - mysql_table: table2
    mongo_collection: collection2